import localFont from "next/font/local";
import "./globals.css";
import { GlobalContextProvider } from "@/services/GlobalContext";
import Navbar from "@/components/general/Navbar";
import Footer from "@/components/general/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Safety on Roads",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <GlobalContextProvider>
      <html lang="en">
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Navbar />
          {children}
          <Footer />
        </body>
      </html>
    </GlobalContextProvider>
  );
}
